[tool]
[tool.poetry]
name = "SpaceUserbot_Deployer"
version = "1.0"
description = "Automatic Deploy SpaceUserBot to Heroku"
authors = ["Miri <Miri@TheMiri.tech>"]
[tool.poetry.dependencies]
python = "^3.8"
bs4 = "*"
gitpython = "*"
heroku3 = "*"
requests = "*"
rich = "*"
telethon = "*"
